In [176]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score
from sklearn.multiclass import OneVsOneClassifier
train=pd.read_csv(r'C:\Users\Rahul\Desktop\train.csv')
test=pd.read_csv(r'C:\Users\Rahul\Desktop\test.csv')

In [177]:
train.head()
test1=test

In [178]:
test.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [179]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
Severity                   10000 non-null object
Safety_Score               10000 non-null float64
Days_Since_Inspection      10000 non-null int64
Total_Safety_Complaints    10000 non-null int64
Control_Metric             10000 non-null float64
Turbulence_In_gforces      10000 non-null float64
Cabin_Temperature          10000 non-null float64
Accident_Type_Code         10000 non-null int64
Max_Elevation              10000 non-null float64
Violations                 10000 non-null int64
Adverse_Weather_Metric     10000 non-null float64
Accident_ID                10000 non-null int64
dtypes: float64(6), int64(5), object(1)
memory usage: 937.6+ KB


In [180]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
Safety_Score               2500 non-null float64
Days_Since_Inspection      2500 non-null int64
Total_Safety_Complaints    2500 non-null int64
Control_Metric             2500 non-null float64
Turbulence_In_gforces      2500 non-null float64
Cabin_Temperature          2500 non-null float64
Accident_Type_Code         2500 non-null int64
Max_Elevation              2500 non-null float64
Violations                 2500 non-null int64
Adverse_Weather_Metric     2500 non-null float64
Accident_ID                2500 non-null int64
dtypes: float64(6), int64(5)
memory usage: 214.9 KB


In [181]:
test.isnull().sum()

Safety_Score               0
Days_Since_Inspection      0
Total_Safety_Complaints    0
Control_Metric             0
Turbulence_In_gforces      0
Cabin_Temperature          0
Accident_Type_Code         0
Max_Elevation              0
Violations                 0
Adverse_Weather_Metric     0
Accident_ID                0
dtype: int64

In [182]:
ohe=OneHotEncoder(sparse=False)

In [183]:
pd.DataFrame(ohe.fit_transform(pd.DataFrame(train[['Severity']]))).head()

0    1    2    3
0  0.0  1.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  0.0  0.0  1.0  0.0

In [184]:
le=LabelEncoder()
train.Severity=le.fit_transform(train.Severity)

In [185]:
#train.Severity=pd.get_dummies(train['Severity'],drop_first=True)
label=train['Severity']

In [186]:
label.value_counts()

0    3049
3    2729
1    2527
2    1695
Name: Severity, dtype: int64

In [187]:
train.isnull().sum()

Severity                   0
Safety_Score               0
Days_Since_Inspection      0
Total_Safety_Complaints    0
Control_Metric             0
Turbulence_In_gforces      0
Cabin_Temperature          0
Accident_Type_Code         0
Max_Elevation              0
Violations                 0
Adverse_Weather_Metric     0
Accident_ID                0
dtype: int64

In [188]:
train=train.drop('Severity',axis=1)

In [189]:
train=train.drop('Accident_ID',axis=1)
test=test.drop('Accident_ID',axis=1)

In [190]:
train=train.astype(np.int64)

In [191]:
test=test.astype(np.int64)

In [192]:
#train1.drop(columns=['Severity'],axis=1,inplace=True)

In [193]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [194]:
ss=StandardScaler()

In [195]:
uj=ss.fit_transform(train)
ut=ss.fit_transform(test)

E:\New folder\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
E:\New folder\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
E:\New folder\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
E:\New folder\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [196]:
uj

array([[ 0.47192239,  0.30198105,  2.2140724 , ..., -0.07064608,
         0.94987305, -0.28769302],
       [ 1.27689144, -0.82808182,  2.93126449, ..., -0.63375798,
        -0.01173158, -0.28769302],
       [ 1.33881214,  0.01946533,  1.35344189, ...,  0.77057587,
         0.94987305, -0.28769302],
       ...,
       [-0.89033292,  1.1495282 , -0.79813439, ...,  0.18763684,
         0.94987305, -0.28769302],
       [ 0.90536727, -1.39311325, -0.94157281, ...,  0.828997  ,
        -0.01173158, -0.28769302],
       [ 0.53384309,  0.01946533, -0.51125756, ..., -0.6357725 ,
        -0.01173158, -0.28769302]])

In [197]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(uj,label,test_size=0.2,random_state=50)

In [198]:
rfc=RandomForestClassifier()
rfc.fit(xtrain,ytrain)

E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [199]:
rfc.score(xtrain,ytrain)

0.996125

In [200]:
rfc.predict(xtest)

array([3, 3, 2, ..., 0, 1, 2])

In [201]:
from sklearn.multiclass import OneVsRestClassifier
orc=OneVsRestClassifier(RandomForestClassifier())

In [202]:
orc.fit(xtrain,ytrain)

E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


OneVsRestClassifier(estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          n_jobs=None)

In [203]:
orc.score(xtrain,ytrain)

0.9995

In [204]:
ypred=orc.predict(xtest)

In [205]:
ynpred=rfc.predict(xtest)

In [206]:
ynpred

array([3, 3, 2, ..., 0, 1, 2])

In [207]:
ypred

array([3, 3, 2, ..., 0, 1, 2])

In [208]:
cvscore=cross_val_score(orc,xtrain,ytrain,cv=3)

E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will ch

In [209]:
cvscore.mean()

0.8998773229109137

In [210]:
final=orc.predict(ut)

In [211]:
newseverity=pd.Series(final)

In [212]:
newseverity.replace({0:'Highly_Fatal_And_Damaging',1:'Minor_Damage_And_Injuries',2:'Significant_Damage_And_Fatalities',3:'Significant_Damage_And_Serious_Injuries'},inplace=True)

In [213]:
testn=pd.concat([test1,newseverity],axis=1)

In [214]:
test1.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [215]:
testn.rename(columns={0:'Severity'},inplace=True)

In [216]:
testn.sort_index(axis=1).head()

Accident_ID  Accident_Type_Code  Adverse_Weather_Metric  Cabin_Temperature  \
0            1                   4                0.069692              78.32   
1           10                   7                0.002777              78.60   
2           14                   6                0.004316              86.96   
3           17                   3                0.199990              80.86   
4           21                   2                0.483696              79.22   

   Control_Metric  Days_Since_Inspection  Max_Elevation  Safety_Score  \
0       72.151322                     16   37949.724386     19.497717   
1       64.585232                     15   30194.805567     58.173516   
2       64.721969                     15   17572.925484     33.287671   
3       66.362808                     21   40209.186341      3.287671   
4       56.107566                     18   35495.525408     10.867580   

                                  Severity  Total_Safety_Complaints  \
0                Highly_Fatal_And_Damaging                        6   
1        Significant_Damage_And_Fatalities                        3   
2  Significant_Damage_And_Serious_Injuries                        3   
3                Highly_Fatal_And_Damaging                        5   
4        Significant_Damage_And_Fatalities                        2   

   Turbulence_In_gforces  Violations  
0               0.388959           2  
1               0.250841           2  
2               0.336669           1  
3               0.421775           2  
4               0.313228           2

In [217]:
test11=pd.concat([testn.Accident_ID,testn.Severity],axis=1)

In [218]:
test11.head()

Accident_ID                                 Severity
0            1                Highly_Fatal_And_Damaging
1           10        Significant_Damage_And_Fatalities
2           14  Significant_Damage_And_Serious_Injuries
3           17                Highly_Fatal_And_Damaging
4           21        Significant_Damage_And_Fatalities

In [221]:
test11.to_csv("Results.csv",index=False)

In [168]:
testn.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Violations  Accident_ID  \
0                   4           2            1   
1                   7           2           10   
2                   6           1           14   
3                   3           2           17   
4                   2           2           21   

                                  Severity  
0                Highly_Fatal_And_Damaging  
1        Significant_Damage_And_Fatalities  
2  Significant_Damage_And_Serious_Injuries  
3                Highly_Fatal_And_Damaging  
4        Significant_Damage_And_Fatalities

In [171]:
testn.to_csv("Results.csv",param=False)

TypeError: to_csv() got an unexpected keyword argument 'param'

In [164]:
cvpredict=cross_val_predict(orc,xtrain,ytrain,cv=3)

E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
E:\New folder\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will ch

In [37]:
ypred

array([3, 0, 1, ..., 0, 0, 0])

In [38]:
cvpredict

array([3, 0, 1, ..., 1, 0, 0])

In [184]:
from sklearn.model_selection import GridSearchCV

In [206]:
param_grid=[{'epsilon':[0.1],'l1_ratio':[0.15,0.20],'penalty':['l1','l2','l3','l4'],'validation_fraction':[0.1,0.3,0.5,0.7]}]

In [207]:
gscvn=GridSearchCV(rfc,param_grid,cv=3) 

In [208]:
gscvn.fit(xtrain,ytrain)

ValueError: Invalid parameter l1_ratio for estimator OneVsRestClassifier(estimator=SGDClassifier(alpha=0.0001, average=False, class_weight=None,
       early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
       l1_ratio=0.15, learning_rate='optimal', loss='hinge', max_iter=None,
       n_iter=None, n_iter_no_change=5, n_jobs=None, penalty='l2',
       power_t=0.5, random_state=None, shuffle=True, tol=None,
       validation_fraction=0.1, verbose=0, warm_start=False),
          n_jobs=None). Check the list of available parameters with `estimator.get_params().keys()`.

In [205]:
from sklearn.model_selection import cross_val_score
cvs=cross_val_score(rfc,xtrain,ytrain,cv=3,scoring='accuracy')

E:\New folder\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
E:\New folder\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
E:\New folder\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not Non

In [178]:
cvs.mean()

0.581709075562854

In [179]:
rfc.score(xtrain,ytrain)

0.7455

In [180]:
rfc.predict(xtest)
rfcn.score(ytest,rfcn)

NameError: name 'rfcn' is not defined

In [ ]:
maxel=pip.fit_transform(xtrain)

In [ ]:
cross_val_score(rfc,maxel,ytrain,cv=10,scoring='accuracy').mean()

In [ ]:
from sklearn.model_selection import cross_val_predict
cvpp=cross_val_predict(rfc,xtrain,ytrain,cv=3)

In [ ]:
from sklearn.metrics import f1_score
f1_score(ytrain,cvpp)